### ISSUE TITLE
Turbo Intruder CLI java.lang.NullPointerException

### ISSUE THREAD

**Issue by hostfree23434** [PortSwigger/http-request-smuggler#56]
Hi,

i used this:
`java -jar turbo-intruder-all.jar sc.py req.txt https://www.google.com foooo`

and output is:

```Please note that Turbo Intruder's SSL/TLS handling may differ slightly when run outside Burp Suite.

ID | Word | Status | Wordcount | Length | Time

Starting attack...

failed to read from clipboard

Establishing 1 connection to https://www.google.com ...

java.lang.NullPointerException: Cannot invoke "burp.IExtensionHelpers.stringToBytes(String)" because "burp.Utils.helpers" is null

        at burp.Request.getRequestAsBytes(Request.kt:98)

        at burp.ThreadedRequestEngine.sendRequests(ThreadedRequestEngine.kt:212)

        at burp.ThreadedRequestEngine.access$sendRequests(ThreadedRequestEngine.kt:17)

        at burp.ThreadedRequestEngine$1.invoke(ThreadedRequestEngine.kt:50)

        at burp.ThreadedRequestEngine$1.invoke(ThreadedRequestEngine.kt:49)

        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Ignoring error: java.lang.NullPointerException: Cannot invoke "burp.IExtensionHelpers.stringToBytes(String)" because "burp.Utils.helpers" is null

1 |  | 0 | 1 | 4 | 0

Completed attack on https://www.google.com

Sent 0 requests over 2 connections in 0.0 seconds

RPS: NaN



Reqs: 0 | Queued: 0 | Duration: 0 | RPS: NaN | Connections: 2 | Retries: 0 | Fails: 1 | Next: null | Completed```



Whats problem?



Regards.

**Comment by albinowax** [comment]
There's a bug in that version of turbo intruder that prevents it from being used on the command line. For command line use, build and run this source: https://github.com/PortSwigger/turbo-intruder

**Comment by hostfree23434** [comment]
Hi albinowax,
Thanks for fast response.
How can do it?

Regards.

**Comment by albinowax** [comment]
Just follow the build instructions in the readme. Sorry, I can't provide more in depth support than that.

**Comment by hostfree23434** [comment]
Thank you.
