### ISSUE TITLE
NullPointerException on montoya API when running scan on Burp Suite Pro (Early Adopter Channel)

### ISSUE THREAD

**Issue by Khara-h1** [PortSwigger/http-request-smuggler#60]
Hi,
thank you for this awesome extension.
I decided to go for the not so stable update and stumbled upon the following error which seems to indicate that the extension isn't yet fully compatible with the new Montoya API.

Just got this error :
```
java.lang.NullPointerException: Cannot invoke "burp.api.montoya.http.message.responses.HttpResponse.copyToTempFile()" because "this.q" is null
	at burp.wnc.i(Unknown Source)
	at burp.kqv.saveBuffersToTempFiles(Unknown Source)
	at burp.yur.saveBuffersToTempFiles(Unknown Source)
	at burp.elb.saveBuffersToTempFiles(Unknown Source)
	at burp.yfv.saveBuffersToTempFiles(Unknown Source)
	at burp.BulkScanItem.<init>(BulkScanItem.java:11)
	at burp.BulkScan.run(BulkScan.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "burp.api.montoya.http.message.responses.HttpResponse.copyToTempFile()" because "this.q" is null
	at burp.wnc.i(Unknown Source)
	at burp.kqv.saveBuffersToTempFiles(Unknown Source)
	at burp.yur.saveBuffersToTempFiles(Unknown Source)
	at burp.elb.saveBuffersToTempFiles(Unknown Source)
	at burp.yfv.saveBuffersToTempFiles(Unknown Source)
	at burp.BulkScanItem.<init>(BulkScanItem.java:11)
	at burp.BulkScan.run(BulkScan.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by albinowax** [comment]
Thanks, I'll pass that along to the API people

**Comment by albinowax** [comment]
Good news, a Burp release coming out in the next few days should fix this.
